# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: artifact

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * 1-6'


env:
  FILE_NAME: hello-server
  DOWNLOAD_PATH_L: /home/runner/work/aula-05-artifact/aula-05-artifact/linux
  DOWNLOAD_PATH_W: D:\a\aula-05-artifact\aula-05-artifact/windows

jobs:

  build-go:
    name: Buildo Go
    runs-on: ubuntu-latest
    steps:
    - name: Chekout Go code
      uses: actions/checkout@v4

    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go
      
    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for windows
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe

  Job1:
    name: download-and-run-linux
    needs: build-go
    runs-on: ubuntu-latest
    
    steps:
    - name: Chekout repo for download
      uses: actions/checkout@v4
      
    - name: download linux
      uses: actions/download-artifact@v4
      with:
        pattern: linux
    
    - run: ls ${{ env.DOWNLOAD_PATH_L }}
    
    - name: opcoes run
      run: source ./run.sh ${{ env.DOWNLOAD_PATH_L }}${{ env.FILE_NAME }}

  Job2:
    name: download-windows
    needs: build-go
    runs-on: windows-latest
    
    steps:
    - name: Chekout repo for download
      uses: actions/checkout@v4
      
    - name: download windows
      uses: actions/download-artifact@v4
      with:
        pattern: windows
        
    - run: ls ${{ env.DOWNLOAD_PATH_W }}
