# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: artifact

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '15 * * * 1-6'


env:
  FILE_NAME: hello-server

jobs:

  build-go:
    name: Buildo Go
    runs-on: ubuntu-latest
    steps:
    - name: Chekout Go code
      uses: actions/checkout@v4

    - name: Build ${{ env.FILE_NAME }} for ubuntu-latest
      run: go build ${{ env.FILE_NAME }}.go
      
    - name: Build ${{ env.FILE_NAME }} for windows-latest
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for windows
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe

  Job1:
    name: download-and-run-linux
    needs: build-go
    runs-on: ubuntu-latest
    
    steps:
    - name: Chekout repo for download
      uses: actions/checkout@v4
      
    - name: download
      uses: actions/download-artifact@v4
      with:
        path: ./teste
        pattern: linux
    
    - run: ls
    
    - name: opcoes run
      run: source ./run.sh

    







#    1º JOB

#- Identificador: download-and-run-linux
#- Name: Download and run Linux
#- Runner: ubuntu (última versão)
#- Primeiro Step: usar a action de checkout no repo
#- Segundo Step: usar a action de download do artefato, passando como argumento o nome do artefato chamado linux, gerado durante o exercício
#- Terceiro Step: executar no S.O o comando para ler as opções do script run.sh (comando: source ./run.sh)

#2º JOB

#- Identificador: download-only-windows
#- Name: Download Windows
#- Runner: windows (última versão)
#- Primeiro Step: usar a action de checkout no repo
#- Segundo Step: usar a action de download do artefato, passando como argumento o nome do artefato chamado windows, gerado durante o exercício
    
